#-----------------------------------------------------------------------------------------------------------------------
#   Kafka Environment: kafka-docker with Kafka and Zookeeper
#   https://hub.docker.com/r/bitnami/kafka
#   https://hub.docker.com/r/bitnami/zookeeper
#   https://github.com/provectus/kafka-ui
#-----------------------------------------------------------------------------------------------------------------------

version: '2'
services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CONTROLLER_LISTENERS=PLAINTEXT://:9093
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181  # Change this line
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_ENABLE_KRAFT=no
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,PLAINTEXT://:9093
      - KAFKA_CFG_REPLICA_FETCH_MAX_BYTES=10485760
      - KAFKA_CFG_MAX_REQUEST_SIZE=10485760
    volumes:
      - kafka-data:/bitnami/kafka
  spectre_producer_anomaly_detector:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - kafka
    volumes:
      - /home/aryn/spectre-dev/spectre-code/spectre-ann/prototype:/prototype  # Bind the local directory to the /spectre directory in the container
  spectre_streamlit_server:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    ports:
      - '8501:8501'
    depends_on:
      - spectre_producer_anomaly_detector
    volumes:
      - /home/aryn/spectre-dev/spectre-code/spectre-ann/prototype:/prototype  # Bind the local directory to the /spectre directory in the container
      #- - ~/prototype:/prototype # Use this for Raspberry Pi Deployement
volumes:
  kafka-data:


