#-----------------------------------------------------------------------------------------------------------------------
#   Kafka Environment: kafka-docker with kafka-ui
#   https://hub.docker.com/r/bitnami/kafka
#   https://hub.docker.com/r/bitnami/zookeeper
#   https://github.com/provectus/kafka-ui
#-----------------------------------------------------------------------------------------------------------------------

version: '2'
services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_CONTROLLER_LISTENERS=PLAINTEXT://:9093
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181  # Change this line
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_ENABLE_KRAFT=no
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,PLAINTEXT://:9093
      - KAFKA_CFG_REPLICA_FETCH_MAX_BYTES=10485760
      - KAFKA_CFG_MAX_REQUEST_SIZE=10485760
    volumes:
      - kafka-data:/bitnami/kafka
  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - 9090:8080
    environment:
      - DYNAMIC_CONFIG_ENABLED=true
    volumes:
      - /home/aryn/spectre-dev/kafka-docker/kui/config.yml:/etc/kafkaui/dynamic_config.yml
volumes:
  kafka-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/aryn/spectre-dev/kafka-docker/kafka-data

