version: '1.0'
services:
  jupyter-lab:
    build: .
    ports:
      - "8888:8888"
    volumes:
      - /home/aryn/spectre-dev/spectre-code:/spectre-code
      - /mnt/c/SPECTRE/Dataset:/spectre-code/dataset
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 0
              capabilities: [ gpu ]
        #limits:
          #nvidia.com/gpu: 4G