version: '1.2'
#volumes:
  #spectre-dev-volume:
services:
  jupyter-lab:
    #container_name: spectre-container
    build: .
    ports:
      - "8888:8888"
    volumes:
      #- /home/aryn/spectre-dev/spectre-code:/spectre-code
      #- /mnt/c/SPECTRE/Dataset:/spectre-code/dataset
      - /home/aryn/spectre-dev/spectre-code:/spectre-code
      - /home/aryn/spectre-dev/dataset:/spectre-code/dataset
      #- spectre-dev-volume:/
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
        limits:
          memory: 16g
