version: '1.2'
services:
  spectre-jupyterlab:
    build: .
    ports:
      - "8888:8888"
    volumes:
      - /home/aryn/spectre-dev/spectre-code:/spectre-code
      - /home/aryn/spectre-dev/dataset:/spectre-code/dataset
      #- /home/aryn/spectre-dev/spectre-code:/spectre-code
      #- /home/aryn/spectre-dev/dataset:/spectre-code/dataset
      #- spectre-dev-volume:/
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
        limits:
          memory: 16g
